### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by clentfort** [jonas-koeritz/xpro-rtp#1]
Hi, sorry for abusing an issue for a thanks, but your blog fails to load disqus. Anyway thanks for your blog post and code I was able to stream the live-preview of my "Birca B-Pro5 Alpha AE" to my computer. :)

**Comment by jonas-koeritz** [comment]
Disqus works fine if accesed via the correct subdomain. If anybody knows
how to setup a wildcard or multiple subdomains in disqus it would help me a
lot.
Thanks for commenting :)

https://blog.jonaskoeritz.de/2017/02/21/hacking-the-xpro2-action-camera/

C Lentfort <notifications@github.com> schrieb am Sa., 10. Feb. 2018, 16:31:
