### ISSUE TITLE
Not Working on my Camera

### ISSUE THREAD

**Issue by mattigins** [jonas-koeritz/xpro-rtp#3]
So i am trying to get this working and judging from your code, it is relatively the same process.

However vlc will not stream it at all (buffer deadlock prevented) and using "ffplay 127.0.0.1:8888" results in a messed up image not recognizable at all.

I am wondering if i could share my pcap file to try and figure this out?

**Comment by jonas-koeritz** [comment]
Hi, this project has been replaced by a new version. I didn't have a look at your pcap file yet but there is a good chance it is compatible or I could add compatibility. See [jonas-koeritz/actioncam](https://github.com/jonas-koeritz/actioncam) for more details.
